### ISSUE TITLE
wrong members accessed from webcolors package

### ISSUE THREAD

**Issue by oblitum** [Danielhiversen/flux_led#72]
Not sure what webcolors version is expected, but:

```
❯ flux_led --listcolors
Traceback (most recent call last):
  File "/home/francisco/.local/bin/flux_led", line 8, in <module>
    sys.exit(main())
  File "/home/francisco/.pyenv/versions/flux_led/lib/python3.9/site-packages/flux_led/__main__.py", line 1718, in main
    (options, args) = parseArgs()
  File "/home/francisco/.pyenv/versions/flux_led/lib/python3.9/site-packages/flux_led/__main__.py", line 1655, in parseArgs
    for c in utils.get_color_names_list():
  File "/home/francisco/.pyenv/versions/flux_led/lib/python3.9/site-packages/flux_led/__main__.py", line 110, in get_color_names_list
    for key in list(webcolors.css2_hex_to_names.keys()):
AttributeError: module 'webcolors' has no attribute 'css2_hex_to_names'
```

This member exists in uppercase (`CSS2_HEX_TO_NAMES`), not lowercase.

**Comment by oblitum** [comment]
This commit invalidates lowercase variants: https://github.com/ubernostrum/webcolors/commit/549107493571e7b1b0a486019b6c429b8cd815f6#diff-49a04a22e692f44290edc8368dae052fcdfb637da2d9fbc78522ce6f1916062f.
